---
title: "git_00"
author: "Monica Hardin"
date: "Year 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Five little girls of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.  
Five rosy girls, in years from Ten to Six:  
Sitting down to lessons—no more time for tricks.  
  
Five growing girls, from Fifteen to Eleven:  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire. 
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,  
      Shining with all his might:  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If we must die--let it not be like hogs. 
Hunted and penned in an inglorious spot,  
While round us bark the mad and hungry dogs,  
Making their mock at our accursed lot.  
If we must die, O let us nobly die,  
So that our precious blood may not be shed. 
In vain; then even the monsters we defy. 
Shall be constrained to honor us though dead!  
O Kinsmen! We must meet the common foe!  
Though far outnumbered, let us show us brave,  
And for their thousand blows deal one deathblow!  
What though before us lies the open grave?  
Like men we'll face the murderous, cowardly pack,  
Pressed to the wall, dying, but fighting back!  
